  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - devopsconf2018
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
empty_count:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 1000

cyclomatic_complexity:
  warning: 10
  error: 50
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 50
  excluded: iPhone # excluded via string

function_parameter_count:
  warning: 8

identifier_name:
  min_length: # only min_length
    warning: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

function_body_length:
  warning: 50 # warning and error

reporter: "xcode"  # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

whitelist_rules: # some rules are only whitelist_rules
  - control_statement
  # - colon
  - comma
  #- type_name
  - nesting
  - function_parameter_count
  - weak_delegate
  - cyclomatic_complexity
  - vertical_whitespace
  - function_body_length
  #- line_length
  - for_where
  - unused_optional_binding
  - implicit_return
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_string
  - fallthrough
  - fatal_error_message
  - first_where
  - force_cast
  # - force_unwrapping

############### ALL RULES #################################
# https://github.com/realm/SwiftLint/blob/master/Rules.md #
###########################################################
